// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.4
// source: dogs.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Requests
type CreateDogRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Breed string `protobuf:"bytes,2,opt,name=breed,proto3" json:"breed,omitempty"`
	Dob   string `protobuf:"bytes,3,opt,name=dob,proto3" json:"dob,omitempty"`
}

func (x *CreateDogRequest) Reset() {
	*x = CreateDogRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dogs_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateDogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDogRequest) ProtoMessage() {}

func (x *CreateDogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dogs_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDogRequest.ProtoReflect.Descriptor instead.
func (*CreateDogRequest) Descriptor() ([]byte, []int) {
	return file_dogs_proto_rawDescGZIP(), []int{0}
}

func (x *CreateDogRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateDogRequest) GetBreed() string {
	if x != nil {
		return x.Breed
	}
	return ""
}

func (x *CreateDogRequest) GetDob() string {
	if x != nil {
		return x.Dob
	}
	return ""
}

type RetrieveDogRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *RetrieveDogRequest) Reset() {
	*x = RetrieveDogRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dogs_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RetrieveDogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveDogRequest) ProtoMessage() {}

func (x *RetrieveDogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dogs_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveDogRequest.ProtoReflect.Descriptor instead.
func (*RetrieveDogRequest) Descriptor() ([]byte, []int) {
	return file_dogs_proto_rawDescGZIP(), []int{1}
}

func (x *RetrieveDogRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type UpdateDogRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Breed string `protobuf:"bytes,2,opt,name=breed,proto3" json:"breed,omitempty"`
	Dob   string `protobuf:"bytes,3,opt,name=dob,proto3" json:"dob,omitempty"`
}

func (x *UpdateDogRequest) Reset() {
	*x = UpdateDogRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dogs_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateDogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDogRequest) ProtoMessage() {}

func (x *UpdateDogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dogs_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDogRequest.ProtoReflect.Descriptor instead.
func (*UpdateDogRequest) Descriptor() ([]byte, []int) {
	return file_dogs_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateDogRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateDogRequest) GetBreed() string {
	if x != nil {
		return x.Breed
	}
	return ""
}

func (x *UpdateDogRequest) GetDob() string {
	if x != nil {
		return x.Dob
	}
	return ""
}

type DeleteDogRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *DeleteDogRequest) Reset() {
	*x = DeleteDogRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dogs_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteDogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDogRequest) ProtoMessage() {}

func (x *DeleteDogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dogs_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDogRequest.ProtoReflect.Descriptor instead.
func (*DeleteDogRequest) Descriptor() ([]byte, []int) {
	return file_dogs_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteDogRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateDogResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *CreateDogResponse) Reset() {
	*x = CreateDogResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dogs_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateDogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDogResponse) ProtoMessage() {}

func (x *CreateDogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dogs_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDogResponse.ProtoReflect.Descriptor instead.
func (*CreateDogResponse) Descriptor() ([]byte, []int) {
	return file_dogs_proto_rawDescGZIP(), []int{4}
}

func (x *CreateDogResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RetrieveDogResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string                   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Dog     *RetrieveDogResponse_Dog `protobuf:"bytes,2,opt,name=dog,proto3" json:"dog,omitempty"`
}

func (x *RetrieveDogResponse) Reset() {
	*x = RetrieveDogResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dogs_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RetrieveDogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveDogResponse) ProtoMessage() {}

func (x *RetrieveDogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dogs_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveDogResponse.ProtoReflect.Descriptor instead.
func (*RetrieveDogResponse) Descriptor() ([]byte, []int) {
	return file_dogs_proto_rawDescGZIP(), []int{5}
}

func (x *RetrieveDogResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RetrieveDogResponse) GetDog() *RetrieveDogResponse_Dog {
	if x != nil {
		return x.Dog
	}
	return nil
}

type UpdateDogResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *UpdateDogResponse) Reset() {
	*x = UpdateDogResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dogs_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateDogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDogResponse) ProtoMessage() {}

func (x *UpdateDogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dogs_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDogResponse.ProtoReflect.Descriptor instead.
func (*UpdateDogResponse) Descriptor() ([]byte, []int) {
	return file_dogs_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateDogResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DeleteDogResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *DeleteDogResponse) Reset() {
	*x = DeleteDogResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dogs_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteDogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDogResponse) ProtoMessage() {}

func (x *DeleteDogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dogs_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDogResponse.ProtoReflect.Descriptor instead.
func (*DeleteDogResponse) Descriptor() ([]byte, []int) {
	return file_dogs_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteDogResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RetrieveDogResponse_Dog struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name       string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Breed      string `protobuf:"bytes,2,opt,name=breed,proto3" json:"breed,omitempty"`
	Dob        string `protobuf:"bytes,3,opt,name=dob,proto3" json:"dob,omitempty"`
	HumanYears int64  `protobuf:"varint,4,opt,name=humanYears,proto3" json:"humanYears,omitempty"`
}

func (x *RetrieveDogResponse_Dog) Reset() {
	*x = RetrieveDogResponse_Dog{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dogs_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RetrieveDogResponse_Dog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveDogResponse_Dog) ProtoMessage() {}

func (x *RetrieveDogResponse_Dog) ProtoReflect() protoreflect.Message {
	mi := &file_dogs_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveDogResponse_Dog.ProtoReflect.Descriptor instead.
func (*RetrieveDogResponse_Dog) Descriptor() ([]byte, []int) {
	return file_dogs_proto_rawDescGZIP(), []int{5, 0}
}

func (x *RetrieveDogResponse_Dog) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RetrieveDogResponse_Dog) GetBreed() string {
	if x != nil {
		return x.Breed
	}
	return ""
}

func (x *RetrieveDogResponse_Dog) GetDob() string {
	if x != nil {
		return x.Dob
	}
	return ""
}

func (x *RetrieveDogResponse_Dog) GetHumanYears() int64 {
	if x != nil {
		return x.HumanYears
	}
	return 0
}

var File_dogs_proto protoreflect.FileDescriptor

var file_dogs_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x64, 0x6f, 0x67, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x64, 0x6f,
	0x67, 0x73, 0x22, 0x4e, 0x0a, 0x10, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x6f, 0x67, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x62, 0x72,
	0x65, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x62, 0x72, 0x65, 0x65, 0x64,
	0x12, 0x10, 0x0a, 0x03, 0x64, 0x6f, 0x62, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x64,
	0x6f, 0x62, 0x22, 0x28, 0x0a, 0x12, 0x52, 0x65, 0x74, 0x72, 0x69, 0x65, 0x76, 0x65, 0x44, 0x6f,
	0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x4e, 0x0a, 0x10,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x6f, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x62, 0x72, 0x65, 0x65, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x62, 0x72, 0x65, 0x65, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x6f,
	0x62, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x64, 0x6f, 0x62, 0x22, 0x26, 0x0a, 0x10,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x44, 0x6f, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x22, 0x2d, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x6f,
	0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x22, 0xc3, 0x01, 0x0a, 0x13, 0x52, 0x65, 0x74, 0x72, 0x69, 0x65, 0x76, 0x65,
	0x44, 0x6f, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x2f, 0x0a, 0x03, 0x64, 0x6f, 0x67, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x64, 0x6f, 0x67, 0x73, 0x2e, 0x52, 0x65, 0x74, 0x72, 0x69, 0x65,
	0x76, 0x65, 0x44, 0x6f, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x44, 0x6f,
	0x67, 0x52, 0x03, 0x64, 0x6f, 0x67, 0x1a, 0x61, 0x0a, 0x03, 0x44, 0x6f, 0x67, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x62, 0x72, 0x65, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x62, 0x72, 0x65, 0x65, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x6f, 0x62, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x64, 0x6f, 0x62, 0x12, 0x1e, 0x0a, 0x0a, 0x68, 0x75, 0x6d,
	0x61, 0x6e, 0x59, 0x65, 0x61, 0x72, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x68,
	0x75, 0x6d, 0x61, 0x6e, 0x59, 0x65, 0x61, 0x72, 0x73, 0x22, 0x2d, 0x0a, 0x11, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x44, 0x6f, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x2d, 0x0a, 0x11, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x44, 0x6f, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0x8a, 0x02, 0x0a, 0x0a, 0x44, 0x6f, 0x67, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3c, 0x0a, 0x09, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x44, 0x6f, 0x67, 0x12, 0x16, 0x2e, 0x64, 0x6f, 0x67, 0x73, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x44, 0x6f, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x64, 0x6f,
	0x67, 0x73, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x6f, 0x67, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x42, 0x0a, 0x0b, 0x52, 0x65, 0x74, 0x72, 0x69, 0x65, 0x76, 0x65,
	0x44, 0x6f, 0x67, 0x12, 0x18, 0x2e, 0x64, 0x6f, 0x67, 0x73, 0x2e, 0x52, 0x65, 0x74, 0x72, 0x69,
	0x65, 0x76, 0x65, 0x44, 0x6f, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e,
	0x64, 0x6f, 0x67, 0x73, 0x2e, 0x52, 0x65, 0x74, 0x72, 0x69, 0x65, 0x76, 0x65, 0x44, 0x6f, 0x67,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3c, 0x0a, 0x09, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x44, 0x6f, 0x67, 0x12, 0x16, 0x2e, 0x64, 0x6f, 0x67, 0x73, 0x2e, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x44, 0x6f, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e,
	0x64, 0x6f, 0x67, 0x73, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x6f, 0x67, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3c, 0x0a, 0x09, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x44, 0x6f, 0x67, 0x12, 0x16, 0x2e, 0x64, 0x6f, 0x67, 0x73, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x44, 0x6f, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x64, 0x6f,
	0x67, 0x73, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x44, 0x6f, 0x67, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x42, 0x32, 0x5a, 0x30, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x62, 0x65, 0x6e, 0x70, 0x61, 0x79, 0x66, 0x6c, 0x69, 0x63, 0x2f, 0x67, 0x72,
	0x70, 0x63, 0x2d, 0x61, 0x70, 0x69, 0x2d, 0x68, 0x65, 0x78, 0x2d, 0x61, 0x72, 0x63, 0x68, 0x2d,
	0x67, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_dogs_proto_rawDescOnce sync.Once
	file_dogs_proto_rawDescData = file_dogs_proto_rawDesc
)

func file_dogs_proto_rawDescGZIP() []byte {
	file_dogs_proto_rawDescOnce.Do(func() {
		file_dogs_proto_rawDescData = protoimpl.X.CompressGZIP(file_dogs_proto_rawDescData)
	})
	return file_dogs_proto_rawDescData
}

var file_dogs_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_dogs_proto_goTypes = []interface{}{
	(*CreateDogRequest)(nil),        // 0: dogs.CreateDogRequest
	(*RetrieveDogRequest)(nil),      // 1: dogs.RetrieveDogRequest
	(*UpdateDogRequest)(nil),        // 2: dogs.UpdateDogRequest
	(*DeleteDogRequest)(nil),        // 3: dogs.DeleteDogRequest
	(*CreateDogResponse)(nil),       // 4: dogs.CreateDogResponse
	(*RetrieveDogResponse)(nil),     // 5: dogs.RetrieveDogResponse
	(*UpdateDogResponse)(nil),       // 6: dogs.UpdateDogResponse
	(*DeleteDogResponse)(nil),       // 7: dogs.DeleteDogResponse
	(*RetrieveDogResponse_Dog)(nil), // 8: dogs.RetrieveDogResponse.Dog
}
var file_dogs_proto_depIdxs = []int32{
	8, // 0: dogs.RetrieveDogResponse.dog:type_name -> dogs.RetrieveDogResponse.Dog
	0, // 1: dogs.DogService.CreateDog:input_type -> dogs.CreateDogRequest
	1, // 2: dogs.DogService.RetrieveDog:input_type -> dogs.RetrieveDogRequest
	2, // 3: dogs.DogService.UpdateDog:input_type -> dogs.UpdateDogRequest
	3, // 4: dogs.DogService.DeleteDog:input_type -> dogs.DeleteDogRequest
	4, // 5: dogs.DogService.CreateDog:output_type -> dogs.CreateDogResponse
	5, // 6: dogs.DogService.RetrieveDog:output_type -> dogs.RetrieveDogResponse
	6, // 7: dogs.DogService.UpdateDog:output_type -> dogs.UpdateDogResponse
	7, // 8: dogs.DogService.DeleteDog:output_type -> dogs.DeleteDogResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_dogs_proto_init() }
func file_dogs_proto_init() {
	if File_dogs_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_dogs_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateDogRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dogs_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RetrieveDogRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dogs_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateDogRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dogs_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteDogRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dogs_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateDogResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dogs_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RetrieveDogResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dogs_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateDogResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dogs_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteDogResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dogs_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RetrieveDogResponse_Dog); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_dogs_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dogs_proto_goTypes,
		DependencyIndexes: file_dogs_proto_depIdxs,
		MessageInfos:      file_dogs_proto_msgTypes,
	}.Build()
	File_dogs_proto = out.File
	file_dogs_proto_rawDesc = nil
	file_dogs_proto_goTypes = nil
	file_dogs_proto_depIdxs = nil
}
