// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.4
// source: dogs.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DogServiceClient is the client API for DogService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DogServiceClient interface {
	CreateDog(ctx context.Context, in *CreateDogRequest, opts ...grpc.CallOption) (*CreateDogResponse, error)
	RetrieveDog(ctx context.Context, in *RetrieveDogRequest, opts ...grpc.CallOption) (*RetrieveDogResponse, error)
	UpdateDog(ctx context.Context, in *UpdateDogRequest, opts ...grpc.CallOption) (*UpdateDogResponse, error)
	DeleteDog(ctx context.Context, in *DeleteDogRequest, opts ...grpc.CallOption) (*DeleteDogResponse, error)
}

type dogServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDogServiceClient(cc grpc.ClientConnInterface) DogServiceClient {
	return &dogServiceClient{cc}
}

func (c *dogServiceClient) CreateDog(ctx context.Context, in *CreateDogRequest, opts ...grpc.CallOption) (*CreateDogResponse, error) {
	out := new(CreateDogResponse)
	err := c.cc.Invoke(ctx, "/dogs.DogService/CreateDog", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dogServiceClient) RetrieveDog(ctx context.Context, in *RetrieveDogRequest, opts ...grpc.CallOption) (*RetrieveDogResponse, error) {
	out := new(RetrieveDogResponse)
	err := c.cc.Invoke(ctx, "/dogs.DogService/RetrieveDog", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dogServiceClient) UpdateDog(ctx context.Context, in *UpdateDogRequest, opts ...grpc.CallOption) (*UpdateDogResponse, error) {
	out := new(UpdateDogResponse)
	err := c.cc.Invoke(ctx, "/dogs.DogService/UpdateDog", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dogServiceClient) DeleteDog(ctx context.Context, in *DeleteDogRequest, opts ...grpc.CallOption) (*DeleteDogResponse, error) {
	out := new(DeleteDogResponse)
	err := c.cc.Invoke(ctx, "/dogs.DogService/DeleteDog", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DogServiceServer is the server API for DogService service.
// All implementations must embed UnimplementedDogServiceServer
// for forward compatibility
type DogServiceServer interface {
	CreateDog(context.Context, *CreateDogRequest) (*CreateDogResponse, error)
	RetrieveDog(context.Context, *RetrieveDogRequest) (*RetrieveDogResponse, error)
	UpdateDog(context.Context, *UpdateDogRequest) (*UpdateDogResponse, error)
	DeleteDog(context.Context, *DeleteDogRequest) (*DeleteDogResponse, error)
	mustEmbedUnimplementedDogServiceServer()
}

// UnimplementedDogServiceServer must be embedded to have forward compatible implementations.
type UnimplementedDogServiceServer struct {
}

func (UnimplementedDogServiceServer) CreateDog(context.Context, *CreateDogRequest) (*CreateDogResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateDog not implemented")
}
func (UnimplementedDogServiceServer) RetrieveDog(context.Context, *RetrieveDogRequest) (*RetrieveDogResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RetrieveDog not implemented")
}
func (UnimplementedDogServiceServer) UpdateDog(context.Context, *UpdateDogRequest) (*UpdateDogResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateDog not implemented")
}
func (UnimplementedDogServiceServer) DeleteDog(context.Context, *DeleteDogRequest) (*DeleteDogResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteDog not implemented")
}
func (UnimplementedDogServiceServer) mustEmbedUnimplementedDogServiceServer() {}

// UnsafeDogServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DogServiceServer will
// result in compilation errors.
type UnsafeDogServiceServer interface {
	mustEmbedUnimplementedDogServiceServer()
}

func RegisterDogServiceServer(s grpc.ServiceRegistrar, srv DogServiceServer) {
	s.RegisterService(&DogService_ServiceDesc, srv)
}

func _DogService_CreateDog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DogServiceServer).CreateDog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dogs.DogService/CreateDog",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DogServiceServer).CreateDog(ctx, req.(*CreateDogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DogService_RetrieveDog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetrieveDogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DogServiceServer).RetrieveDog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dogs.DogService/RetrieveDog",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DogServiceServer).RetrieveDog(ctx, req.(*RetrieveDogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DogService_UpdateDog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DogServiceServer).UpdateDog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dogs.DogService/UpdateDog",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DogServiceServer).UpdateDog(ctx, req.(*UpdateDogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DogService_DeleteDog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DogServiceServer).DeleteDog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dogs.DogService/DeleteDog",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DogServiceServer).DeleteDog(ctx, req.(*DeleteDogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DogService_ServiceDesc is the grpc.ServiceDesc for DogService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DogService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dogs.DogService",
	HandlerType: (*DogServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateDog",
			Handler:    _DogService_CreateDog_Handler,
		},
		{
			MethodName: "RetrieveDog",
			Handler:    _DogService_RetrieveDog_Handler,
		},
		{
			MethodName: "UpdateDog",
			Handler:    _DogService_UpdateDog_Handler,
		},
		{
			MethodName: "DeleteDog",
			Handler:    _DogService_DeleteDog_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dogs.proto",
}
